# permissions for end users to edit clusterassignments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterassignment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rancher-operator-permissions
    app.kubernetes.io/part-of: rancher-operator-permissions
    app.kubernetes.io/managed-by: kustomize
  name: clusterassignment-editor-role
rules:
- apiGroups:
  - permissions.xddevelopment.com
  resources:
  - clusterassignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - permissions.xddevelopment.com
  resources:
  - clusterassignments/status
  verbs:
  - get
