---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - User
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - permissions.xddevelopment.com
  resources:
  - clusterassignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - permissions.xddevelopment.com
  resources:
  - clusterassignments/finalizers
  verbs:
  - update
- apiGroups:
  - permissions.xddevelopment.com
  resources:
  - clusterassignments/status
  verbs:
  - get
  - patch
  - update
